---
- name: restart nginx
  service: name=nginx state=restarted
  ignore_errors: True

- name: restart mysql
  service: name=mysql state=restarted
  ignore_errors: True

- name: restart iptables
  service: name=iptables state=restarted
  ignore_errors: True

- name: restart sshd
  service: name=sshd state=restarted
  ignore_errors: True

- name: restart monit
  service: name=monit state=restarted
  ignore_errors: True
