- hosts: sova_vm
  user: root
  sudo: yes
  roles:
    - sova_vm_remove_phpmyadmin

- hosts: sovafree_vm
  user: root
  sudo: yes
  roles:
    - sova_vm_remove_phpmyadmin

- hosts: sova_vm_test
  user: root
  sudo: yes
  roles:
    - sova_vm_remove_phpmyadmin

- hosts: sovafree_vm_test
  user: root
  sudo: yes
  roles:
    - sova_vm_remove_phpmyadmin

- hosts: sova_vm_template
  user: root
  sudo: yes
  roles:
    - sova_vm_remove_phpmyadmin

- hosts: sovafree_vm_template
  user: root
  sudo: yes
  roles:
    - sova_vm_remove_phpmyadmin

