- hosts: sovafreedev_proxy
  user: root
  roles:
    - sovafree_proxy

- hosts: sovafree_proxy
  user: root
  roles:
    - sovafree_proxy

- hosts: sovafreedev_sftp
  user: root
  roles:
    - sovafree_sftp_sshd

- hosts: sovafree_sftp
  user: root
  roles:
    - sovafree_sftp_sshd
