---
- name: delete log file
  shell: rm -f {{ item }}
  with_items:
  - /var/log/btmp-????????
  - /var/log/cron-????????
  - /var/log/fail2ban.log-????????
  - /var/log/maillog-????????
  - /var/log/messages-????????
  - /var/log/secure-????????
  - /var/log/spooler-????????
  - /var/log/wtmp-????????
  - /var/log/yum.log-????????

- name: delete yum cache
  shell: yum clean all

- name: delete /tmp file
  shell: rm -rf /tmp/*
