---
- name: check if top object exists
  shell: /usr/bin/ldapsearch -x -D {{ midx_domain_root_dn }} -w {{ midx_domain_rootdn_password }} -b {{ midx_domain_suffix }} "dc={{ midx_subdomain }}" | grep "numEntries"
  register: check_top_entry
  failed_when: check_top_entry.rc not in [0, 1]

- name: check if root exists
  shell: /usr/bin/ldapsearch -x -D {{ midx_domain_root_dn }} -w {{ midx_domain_rootdn_password }} -b {{ midx_domain_suffix }} "cn={{ midx_domain_root_cn }}" | grep "numEntries"
  register: check_root_entry
  failed_when: check_root_entry.rc not in [0, 1]

- name: check if Users exists
  shell: /usr/bin/ldapsearch -x -D {{ midx_domain_root_dn }} -w {{ midx_domain_rootdn_password }} -b {{ midx_domain_suffix }} "ou={{ users_ou }}" | grep "numEntries"
  register: check_users_entry
  failed_when: check_users_entry.rc not in [0, 1]

- name: check if Groups exists
  shell: /usr/bin/ldapsearch -x -D {{ midx_domain_root_dn }} -w {{ midx_domain_rootdn_password }} -b {{ midx_domain_suffix }} "ou={{ groups_ou }}" | grep "numEntries"
  register: check_groups_entry
  failed_when: check_groups_entry.rc not in [0, 1]

- name: check if midx group exists
  shell: /usr/bin/ldapsearch -x -D {{ midx_domain_root_dn }} -w {{ midx_domain_rootdn_password }} -b ou={{ groups_ou }},{{ midx_domain_suffix }} "cn={{ midx_group }}" | grep "numEntries"
  register: check_midx_group_entry
  failed_when: check_midx_group_entry.rc not in [0, 1]

- name: check if master map exists
  shell: /usr/bin/ldapsearch -x -D {{ midx_domain_root_dn }} -w {{ midx_domain_rootdn_password }} -b {{ midx_domain_suffix }} "nisMapName=auto.master" | grep "numEntries"
  register: check_master_map_entry
  failed_when: check_master_map_entry.rc not in [0, 1]

- name: check if map for midx group exists
  shell: /usr/bin/ldapsearch -x -D {{ midx_domain_root_dn }} -w {{ midx_domain_rootdn_password }} -b {{ midx_domain_suffix }} "nisMapName=auto.{{ midx_group }}" | grep "numEntries"
  register: check_midx_group_map_entry
  failed_when: check_midx_group_map_entry.rc not in [0, 1]

- name: check if midx group map entry exists
  shell: /usr/bin/ldapsearch -x -D {{ midx_domain_root_dn }} -w {{ midx_domain_rootdn_password }} -b nisMapName=auto.master,{{ midx_domain_suffix }} "cn=/{{ midx_group }}" | grep "numEntries"
  register: check_midx_group_entry_entry
  failed_when: check_midx_group_entry_entry.rc not in [0, 1]

- name: copy ldif file to add users data
  template: src=users.ldif.j2 dest=/tmp/users.ldif owner=root group=root mode=600 force=yes

- name: add users data
  shell: /usr/bin/ldapadd -x -D {{ midx_domain_root_dn }} -w {{ midx_domain_rootdn_password }} -f /tmp/users.ldif

- name: create a base bin directory for backup
  file: path=/root/bin state=directory owner=root group=root mode=0755

- name: create a base directory for backup
  file: path=/root/ldap_backups state=directory owner=root group=root mode=0755

- name: prepare backup file
  copy: src=backup.sh dest=/root/bin/backup.sh owner=root group=root mode=0755

- name: prepare cron_root file
  copy: src=cron_root dest=/var/spool/cron/root owner=root group=root mode=0600
  notify: restart crond
